---
kind: pipeline
type: docker
name: Design Labs Configuration Check

steps:
- name: Lab Parser Check
  image: martimy/netauto:0.2
  commands:
  - python parser_check.py
  when:
    branch:
    - lab?_*

- name: Lab 1-4 Batfish Analysis
  image: martimy/netauto:0.2
  environment:
    BATFISH_SERVER:
      from_secret: batfish_server
  commands:
  - python check_lab_1.py
  when:
    branch:
    - lab1_*
    - lab2_*
    - lab3_*
    - lab4_*

- name: Lab 5 Batfish Analysis
  image: martimy/netauto:0.2
  environment:
    BATFISH_SERVER:
      from_secret: batfish_server
  commands:
  - python check_lab_5.py
  when:
    branch:
    - lab5_*
    
trigger:
  branch:
  - lab?_*

