kind: pipeline
type: docker
name: Network Configuration Check


steps:
- name: Batfish Check
  image: martimy/netauto:0.1
  environment:
    BATFISH_SERVER:
      from_secret: batfish_server
  commands:
  - python assert.py

trigger:
  event:
    - push
