kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Install and deploy
  image: martimy/netauto:0.1
  environment:
    BATFISH_SERVER:
      from_secret: batfish_server
  commands:
  - python assert.py

trigger:
  branch:
    exclude:
    - main
    - master

