---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - hostname -I | awk '{print $1}'

---
kind: pipeline
type: docker
name: Design Labs Configuration Check

steps:
- name: Lab 1 Batfish Analysis
  image: martimy/netauto:0.1
  environment:
    BATFISH_SERVER:
      from_secret: batfish_server
  commands:
  - python check_lab_1.py
  when:
    branch:
    - lab1_*

- name: Lab 2 Batfish Analysis
  image: martimy/netauto:0.1
  environment:
    BATFISH_SERVER:
      from_secret: batfish_server
  commands:
  - python check_lab_1.py
  when:
    branch:
    - lab2_*

trigger:
  branch:
    exclude:
    - master
    - main
    include:
    - lab*
  event:
    - push
