kind: pipeline
type: docker
name: Network Configuration Check


steps:
- name: Batfish Check
  image: martimy/netauto:0.1
  environment:
    BATFISH_SERVER:
      from_secret: batfish_server
  commands:
  - python check_lab_1.py
  when:
    branch:
    - lab1_*

trigger:
  branch:
    exclude:
    - master
    - main
  event:
    - push
