---
kind: pipeline
type: docker
name: Design Labs Configuration Check

steps:
- name: Lab 1 Batfish Analysis
  image: martimy/netauto:0.1
  environment:
    BATFISH_SERVER:
      from_secret: batfish_server
  commands:
  - python check_lab_1.py
  when:
    branch:
    - lab1_*

- name: Lab 2 Batfish Analysis
  - echo "No check is available"
  when:
    branch:
    - lab2_*

trigger:
  branch:
    exclude:
    - master
    - main
    include:
    - lab*
  event:
    - push
